services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=https://sells-appropriate-ut-want.trycloudflare.com
    ports:
      - "8082:8080"
    command: start-dev
    # ใช้จริงไม่ได้ เพราะสร้างแล้วจะหาย 